#!/bin/sh
set -e

LIGHTDM_DEBCONF_KEY=shared/lightdm-greeter

. /usr/share/debconf/confmodule

case "$1" in
configure|upgrade|reconfigure)
    db_get $LIGHTDM_DEBCONF_KEY
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
        /usr/lib/lightdm/lightdm-set-defaults --keep-old --greeter=$RET --session=kde-plasma || true
    fi
    ;;
esac

#DEBHELPER#

